In [1]:
#imports
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
#load data
df = pd.read_csv('df.csv')
df.head()

,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,On_time,Warehouse_block_A,Warehouse_block_B,Warehouse_block_C,Warehouse_block_D,Warehouse_block_F,Mode_of_Shipment_Flight,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Product_importance_high,Product_importance_low,Product_importance_medium,Gender_F
0,4,2,177,3,44,1233,1,0,0,0,1,0,1,0,0,0,1,0,1
1,4,5,216,2,59,3088,1,0,0,0,0,1,1,0,0,0,1,0,0
2,2,2,183,4,48,3374,1,1,0,0,0,0,1,0,0,0,1,0,0
3,3,3,176,4,10,1177,1,0,1,0,0,0,1,0,0,0,0,1,0
4,2,2,184,3,46,2484,1,0,0,1,0,0,1,0,0,0,0,1,1

In [3]:
df.dtypes

Customer_care_calls          int64
Customer_rating              int64
Cost_of_the_Product          int64
Prior_purchases              int64
Discount_offered             int64
Weight_in_gms                int64
On_time                      int64
Warehouse_block_A            int64
Warehouse_block_B            int64
Warehouse_block_C            int64
Warehouse_block_D            int64
Warehouse_block_F            int64
Mode_of_Shipment_Flight      int64
Mode_of_Shipment_Road        int64
Mode_of_Shipment_Ship        int64
Product_importance_high      int64
Product_importance_low       int64
Product_importance_medium    int64
Gender_F                     int64
dtype: object

All of our data is numerical so we can just do a train test split on this. We will do two train test splits, one with On_time as the label and one with Customer_rating as the label.

In [4]:
# train test split for on_time model
X_train_ot, X_test_ot, y_train_ot, y_test_ot = train_test_split(df.drop(columns='On_time'), df.On_time, test_size=0.2, random_state=21)

In [5]:
X_train_ot.shape, X_test_ot.shape

((8799, 18), (2200, 18))

In [6]:
y_train_ot.shape, y_train_ot.shape

((8799,), (8799,))

In [7]:
# scale train set
scaler = StandardScaler()
scaler.fit(X_train_ot)
X_train_ot_scaled = scaler.transform(X_train_ot)
X_train_ot_scaled = pd.DataFrame(X_train_ot_scaled, columns=X_train_ot.columns)
X_train_ot_scaled.head()

,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Warehouse_block_A,Warehouse_block_B,Warehouse_block_C,Warehouse_block_D,Warehouse_block_F,Mode_of_Shipment_Flight,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Product_importance_high,Product_importance_low,Product_importance_medium,Gender_F
0,-0.050069,0.713332,-1.151014,0.283359,-0.206372,1.134459,-0.451142,-0.445841,-0.445291,-0.451689,1.42440,-0.442723,2.289198,-1.444023,-0.304585,1.038353,-0.875507,0.981197
1,-0.931185,0.713332,0.912624,-0.372248,-0.453462,1.277373,2.216598,-0.445841,-0.445291,-0.451689,-0.70205,-0.442723,-0.436834,0.692510,-0.304585,-0.963064,1.142195,-1.019163
2,0.831047,1.421113,0.349813,0.938966,-0.515235,-1.501171,2.216598,-0.445841,-0.445291,-0.451689,-0.70205,-0.442723,-0.436834,0.692510,-0.304585,-0.963064,1.142195,-1.019163
3,0.831047,0.713332,1.308675,-0.372248,-0.453462,0.251826,-0.451142,-0.445841,-0.445291,2.213912,-0.70205,-0.442723,-0.436834,0.692510,-0.304585,-0.963064,1.142195,-1.019163
4,-0.931185,0.005550,-0.067083,2.250181,0.349581,-0.890260,-0.451142,2.242954,-0.445291,-0.451689,-0.70205,2.258748,-0.436834,-1.444023,-0.304585,-0.963064,1.142195,-1.019163

In [8]:
# scale test set
X_test_ot_scaled = scaler.transform(X_test_ot)
X_test_ot_scaled = pd.DataFrame(X_test_ot_scaled, columns=X_test_ot.columns)
X_test_ot_scaled.head()

,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Warehouse_block_A,Warehouse_block_B,Warehouse_block_C,Warehouse_block_D,Warehouse_block_F,Mode_of_Shipment_Flight,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Product_importance_high,Product_importance_low,Product_importance_medium,Gender_F
0,-0.931185,1.421113,0.870934,-1.027856,-0.577007,0.284948,-0.451142,-0.445841,-0.445291,2.213912,-0.70205,-0.442723,-0.436834,0.692510,3.283156,-0.963064,-0.875507,-1.019163
1,-0.050069,0.713332,-1.317772,-0.372248,-0.268145,0.552375,-0.451142,-0.445841,2.245722,-0.451689,-0.70205,2.258748,-0.436834,-1.444023,-0.304585,-0.963064,1.142195,-1.019163
2,-0.931185,0.713332,0.370658,-1.027856,2.017441,-0.200837,2.216598,-0.445841,-0.445291,-0.451689,-0.70205,-0.442723,-0.436834,0.692510,-0.304585,-0.963064,1.142195,-1.019163
3,1.712162,-0.702231,-1.025945,0.283359,-0.268145,-1.384019,-0.451142,2.242954,-0.445291,-0.451689,-0.70205,-0.442723,2.289198,-1.444023,-0.304585,1.038353,-0.875507,0.981197
4,0.831047,-1.410013,-0.796652,-1.027856,-0.391690,0.939408,-0.451142,-0.445841,-0.445291,-0.451689,1.42440,-0.442723,-0.436834,0.692510,3.283156,-0.963064,-0.875507,0.981197

In [9]:
# do train test split and scale data now for customer_rating model
X_train_cr, X_test_cr, y_train_cr, y_test_cr = train_test_split(df.drop(columns='Customer_rating'), df.Customer_rating, test_size=0.2, random_state=21)
scaler = StandardScaler()
scaler.fit(X_train_cr)
X_train_cr_scaled = scaler.transform(X_train_cr)
X_train_cr_scaled = pd.DataFrame(X_train_cr_scaled, columns=X_train_cr.columns)
X_test_cr_scaled = scaler.transform(X_test_cr)
X_test_cr_scaled = pd.DataFrame(X_test_cr_scaled, columns=X_test_cr.columns)

In [10]:
X_train_cr_scaled.head()

,Customer_care_calls,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,On_time,Warehouse_block_A,Warehouse_block_B,Warehouse_block_C,Warehouse_block_D,Warehouse_block_F,Mode_of_Shipment_Flight,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Product_importance_high,Product_importance_low,Product_importance_medium,Gender_F
0,-0.050069,-1.151014,0.283359,-0.206372,1.134459,0.825691,-0.451142,-0.445841,-0.445291,-0.451689,1.42440,-0.442723,2.289198,-1.444023,-0.304585,1.038353,-0.875507,0.981197
1,-0.931185,0.912624,-0.372248,-0.453462,1.277373,-1.211106,2.216598,-0.445841,-0.445291,-0.451689,-0.70205,-0.442723,-0.436834,0.692510,-0.304585,-0.963064,1.142195,-1.019163
2,0.831047,0.349813,0.938966,-0.515235,-1.501171,-1.211106,2.216598,-0.445841,-0.445291,-0.451689,-0.70205,-0.442723,-0.436834,0.692510,-0.304585,-0.963064,1.142195,-1.019163
3,0.831047,1.308675,-0.372248,-0.453462,0.251826,0.825691,-0.451142,-0.445841,-0.445291,2.213912,-0.70205,-0.442723,-0.436834,0.692510,-0.304585,-0.963064,1.142195,-1.019163
4,-0.931185,-0.067083,2.250181,0.349581,-0.890260,0.825691,-0.451142,2.242954,-0.445291,-0.451689,-0.70205,2.258748,-0.436834,-1.444023,-0.304585,-0.963064,1.142195,-1.019163

In [11]:
X_test_cr_scaled.head()

,Customer_care_calls,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,On_time,Warehouse_block_A,Warehouse_block_B,Warehouse_block_C,Warehouse_block_D,Warehouse_block_F,Mode_of_Shipment_Flight,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Product_importance_high,Product_importance_low,Product_importance_medium,Gender_F
0,-0.931185,0.870934,-1.027856,-0.577007,0.284948,0.825691,-0.451142,-0.445841,-0.445291,2.213912,-0.70205,-0.442723,-0.436834,0.692510,3.283156,-0.963064,-0.875507,-1.019163
1,-0.050069,-1.317772,-0.372248,-0.268145,0.552375,0.825691,-0.451142,-0.445841,2.245722,-0.451689,-0.70205,2.258748,-0.436834,-1.444023,-0.304585,-0.963064,1.142195,-1.019163
2,-0.931185,0.370658,-1.027856,2.017441,-0.200837,0.825691,2.216598,-0.445841,-0.445291,-0.451689,-0.70205,-0.442723,-0.436834,0.692510,-0.304585,-0.963064,1.142195,-1.019163
3,1.712162,-1.025945,0.283359,-0.268145,-1.384019,-1.211106,-0.451142,2.242954,-0.445291,-0.451689,-0.70205,-0.442723,2.289198,-1.444023,-0.304585,1.038353,-0.875507,0.981197
4,0.831047,-0.796652,-1.027856,-0.391690,0.939408,-1.211106,-0.451142,-0.445841,-0.445291,-0.451689,1.42440,-0.442723,-0.436834,0.692510,3.283156,-0.963064,-0.875507,0.981197

In [12]:
# save data sets
X_train_ot.to_csv('X_train_ot.csv')
X_test_ot.to_csv('X_test_ot.csv')
y_train_ot.to_csv('y_train_ot.csv')
y_test_ot.to_csv('y_test_ot.csv')
X_train_ot_scaled.to_csv('X_train_ot_scaled.csv')
X_test_ot_scaled.to_csv('X_test_ot_scaled.csv')
X_train_cr.to_csv('X_train_cr.csv')
X_test_cr.to_csv('X_test_cr.csv')
y_train_cr.to_csv('y_train_cr.csv')
y_test_cr.to_csv('y_test_cr.csv')
X_train_cr_scaled.to_csv('X_train_cr_scaled.csv')
X_test_cr_scaled.to_csv('X_test_cr_scaled.csv')